#! /bin/bash -eu
#
# Operate in development environment

cd $(dirname $0)/..

dc_args=()

if [ "$1" = "--service-ports" ]; then
  dc_args+=($1)
  shift
fi

set -x

docker-compose run --rm dev sh -c "bundle check || bundle install"
docker-compose run --rm ${dc_args[@]} dev "${@-bash}"
